import type { Metadata } from 'next'
import { Inter, JetBrains_Mono, Yatra_One } from 'next/font/google'
import './globals.css'

const jetBrainsMono = JetBrains_Mono({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-jetbarins',
	weight: ['400', '700'],
})

const yatraOne = Yatra_One({
	subsets: ['latin'],
	variable: '--font-yatra',
	weight: '400',
})

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
	weight: ['700', '400'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${jetBrainsMono.variable} ${yatraOne.variable} ${inter.variable}`}
			>
				<main className='h-screen'>{children}</main>
			</body>
		</html>
	)
}
